IF NOT EXISTS (SELECT TOP 1 ApplicationId FROM Miscellaneous.Configurations)
BEGIN
	INSERT INTO [Miscellaneous].[Configurations] ([ApplicationID], [Name], [Value], [CreatedOn], [CreatedBy], [ModifiedOn], [ModifiedBy]) VALUES (0, N'invalid-password-attempts-before-lockout', N'3', '20140126 00:48:33.453', N'James', NULL, NULL)
	INSERT INTO [Miscellaneous].[Configurations] ([ApplicationID], [Name], [Value], [CreatedOn], [CreatedBy], [ModifiedOn], [ModifiedBy]) VALUES (5, N'agent-smtp-enable-ssl', N'true', '20140306 20:43:00.000', N'James', NULL, NULL)
	INSERT INTO [Miscellaneous].[Configurations] ([ApplicationID], [Name], [Value], [CreatedOn], [CreatedBy], [ModifiedOn], [ModifiedBy]) VALUES (5, N'agent-smtp-port', N'587', '20140306 20:41:00.000', N'James', NULL, NULL)
	INSERT INTO [Miscellaneous].[Configurations] ([ApplicationID], [Name], [Value], [CreatedOn], [CreatedBy], [ModifiedOn], [ModifiedBy]) VALUES (5, N'agent-smtp-pswd', N'2Rings2RuleThem', '20140306 20:42:00.000', N'James', NULL, NULL)
	INSERT INTO [Miscellaneous].[Configurations] ([ApplicationID], [Name], [Value], [CreatedOn], [CreatedBy], [ModifiedOn], [ModifiedBy]) VALUES (5, N'agent-smtp-server', N'smtp.office365.com', '20140306 20:40:00.000', N'James', NULL, NULL)
	INSERT INTO [Miscellaneous].[Configurations] ([ApplicationID], [Name], [Value], [CreatedOn], [CreatedBy], [ModifiedOn], [ModifiedBy]) VALUES (5, N'agent-smtp-uname', N'admin@trackitsvalue.com', '20140306 20:42:00.000', N'James', NULL, NULL)
	INSERT INTO [Miscellaneous].[Configurations] ([ApplicationID], [Name], [Value], [CreatedOn], [CreatedBy], [ModifiedOn], [ModifiedBy]) VALUES (5, N'new-alerts-email-body', N'<html>
	<head>
	  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	  <style type="text/css">
		body {
		  font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
		  background: ghostwhite;
		}
	
		h1 {
		text-align: center;
		}

		p.MsoNormal, li.MsoNormal, div.MsoNormal {
		  margin: 0in;
		  margin-bottom: .0001pt;
		  font-size: 12.0pt;
		}

		a:link, span.MsoHyperlink {
		  color: #438eb9;
		  text-decoration: underline;
		}

		a:visited, span.MsoHyperlinkFollowed {
		  color: purple;
		  text-decoration: underline;
		}

		span.EmailStyle17 {
		  color: windowtext;
		}

		div.Section1 {
		  margin: 0.2in 1.0in 0.2in 1.0in;
		}	
		
		#alerts-table
		{
			font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
			font-size: 12px;
			margin: 45px;
			width: 480px;
			text-align: left;
			border-collapse: collapse;
		}
		#alerts-table th
		{
			font-size: 13px;
			font-weight: normal;
			padding: 8px;
			background: #b9c9fe url(''table-images/gradhead.png'') repeat-x;
			border-top: 2px solid #d3ddff;
			border-bottom: 1px solid #fff;
			color: #039;
		}
		#alerts-table td
		{
			padding: 8px; 
			border-bottom: 1px solid #fff;
			color: #669;
			border-top: 1px solid #fff;
			background: #e8edff url(''table-images/gradback.png'') repeat-x;
		}
		#alerts-table tfoot tr td
		{
			background: #e8edff;
			font-size: 12px;
			color: #99c;
		}
		#alerts-table tbody tr:hover td
		{
			background: #d0dafd url(''table-images/gradhover.png'') repeat-x;
			color: #339;
		}
	
		.alert-text-warning > tr {
		  color: #d15b47 !important;
		}
	
		.text-r {
			text-align: right;
		}
	
		.text-c {
			text-align: center;
		}
	
	  </style>
	</head>
	<body lang="EN-US">
		<h1><div><span><img alt="$" src="http://trackitsvalue.com/Content/img/XSmallLogo.png"></span><span style="color: #478fca; font-size: 20pt;">trackItsValue.com</span></div></center></h1>
		<div class="Section1">
		<p class="MsoNormal">
		  <b>
			<span style=''font-size: 16.0pt;''>
			  The following alert(s) have just been triggered for your account:
			</span>
		  </b>
		</p>
		<p class="MsoNormal">
		  &nbsp;
		</p>
		<p><center>
		  @alertsTable@
		</center></p>
		<p class="MsoNormal">
		  &nbsp;
		</p>
		<p class="MsoNormal">
		  <span style=''font-size: 9.0pt;''>
			This message has been automatically generated by <span style="color: #478fca; font-size: 10.0pt; font-weight: bold;">trackItsValue.com</span>''s workflow system, please do not reply to
			this message as the mailbox associated with this email is not monitored.
		  </span>
		</p>
	  </div>
	</body>
	</html>', '20170608 23:17:00.000', N'James', NULL, NULL)
	INSERT INTO [Miscellaneous].[Configurations] ([ApplicationID], [Name], [Value], [CreatedOn], [CreatedBy], [ModifiedOn], [ModifiedBy]) VALUES (5, N'new-alerts-email-subject', N'You Have Alerts!', '20170608 23:18:00.000', N'James', NULL, NULL)
	INSERT INTO [Miscellaneous].[Configurations] ([ApplicationID], [Name], [Value], [CreatedOn], [CreatedBy], [ModifiedOn], [ModifiedBy]) VALUES (5, N'new-user-confirmation-email-body', N'<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	  <style type="text/css">
		  body {
			font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
			background: ghostwhite;
		  }
			p.MsoNormal, li.MsoNormal, div.MsoNormal
			{
				margin: 0in;
				margin-bottom: .0001pt;
				font-size: 12.0pt;
			}
			a:link, span.MsoHyperlink
			{
				color:  #438eb9;
				text-decoration: underline;
			}
			a:visited, span.MsoHyperlinkFollowed
			{
				color: purple;
				text-decoration: underline;
			}
			span.EmailStyle17
			{
				color: windowtext;
			}
			div.Section1
			{
				margin: 1.0in 1.0in 1.0in 1.0in;
			}
	  </style>
	</head>
	<body lang="EN-US">
		<div class="Section1">
			<p class="MsoNormal">
				<b>
				<span style=''font-size: 16.0pt;''>
				  The user @UserName@ has just been registered to your email address at <span style="color: #69aa46">$</span><span style="color: #438eb9">trackItsValue.com</span>.</span></b></p>
			<p class="MsoNormal">
				&nbsp;</p>
			<p class="MsoNormal">
			  If you wish to finish registration please click on <a href="http://www.trackItsValue.com/enableUser?UserName=@UserName@&ConfirmationId=@ConfirmationId@">this link</a>.
			</p>  
		  <p class="MsoNormal">
				&nbsp;</p>
			<p class="MsoNormal">
			  <span style=''font-size: 9.0pt;''>This message has been automatically generated by 
				<span style="color: #69aa46; font-size: 10.0pt; font-weight: bold;">$</span><span style="color: #438eb9; font-size: 10.0pt; font-weight: bold;">trackItsValue.com</span>''s workflow system, please do not reply to
					this message as the mailbox associated with this email is not monitored.</span></p>
		</div>
	</body>
	</html>', '20140306 16:10:00.000', N'James', '20140309 12:45:10.990', N'James')
	INSERT INTO [Miscellaneous].[Configurations] ([ApplicationID], [Name], [Value], [CreatedOn], [CreatedBy], [ModifiedOn], [ModifiedBy]) VALUES (5, N'new-user-confirmation-email-subject', N'Confirm your new user at trackItsValue.com', '20140306 16:09:00.000', N'James', NULL, NULL)
	INSERT INTO [Miscellaneous].[Configurations] ([ApplicationID], [Name], [Value], [CreatedOn], [CreatedBy], [ModifiedOn], [ModifiedBy]) VALUES (5, N'redis-cache-connection', N'db03.serenity.dom:6379', '20140324 12:21:00.000', N'James', NULL, NULL)
	INSERT INTO [Miscellaneous].[Configurations] ([ApplicationID], [Name], [Value], [CreatedOn], [CreatedBy], [ModifiedOn], [ModifiedBy]) VALUES (5, N'user-reset-passwrod-email-body', N'<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	  <style type="text/css">
		  body {
			font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
			background: ghostwhite;
		  }
			p.MsoNormal, li.MsoNormal, div.MsoNormal
			{
				margin: 0in;
				margin-bottom: .0001pt;
				font-size: 12.0pt;
			}
			a:link, span.MsoHyperlink
			{
				color:  #438eb9;
				text-decoration: underline;
			}
			a:visited, span.MsoHyperlinkFollowed
			{
				color: purple;
				text-decoration: underline;
			}
			span.EmailStyle17
			{
				color: windowtext;
			}
			div.Section1
			{
				margin: 1.0in 1.0in 1.0in 1.0in;
			}
	  </style>
	</head>
	<body lang="EN-US">
		<div class="Section1">
			<p class="MsoNormal">
				<b>
				<span style=''font-size: 16.0pt;''>
				  A reset password request for @UserName@ has just been registered to your email address at <span style="color: #69aa46">$</span><span style="color: #438eb9">trackItsValue.com</span>.</span></b></p>
			<p class="MsoNormal">
				&nbsp;</p>
			<p class="MsoNormal">
			  If you wish to reset your password please click on <a href="http://www.trackItsValue.com/resetUserPassword?UserName=@UserName@&ConfirmationId=@ConfirmationId@">this link</a>.
			</p>  
		  <p class="MsoNormal">
				&nbsp;</p>
			<p class="MsoNormal">
			  <span style=''font-size: 9.0pt;''>This message has been automatically generated by 
				<span style="color: #69aa46; font-size: 10.0pt; font-weight: bold;">$</span><span style="color: #438eb9; font-size: 10.0pt; font-weight: bold;">trackItsValue.com</span>''s workflow system, please do not reply to
					this message as the mailbox associated with this email is not monitored.</span></p>
		</div>
	</body>
	</html>', '20140905 22:41:40.377', N'James', '20140906 00:28:22.830', N'James')
	INSERT INTO [Miscellaneous].[Configurations] ([ApplicationID], [Name], [Value], [CreatedOn], [CreatedBy], [ModifiedOn], [ModifiedBy]) VALUES (5, N'user-reset-passwrod-email-subject', N'Reset your user at trackItsValue.com', '20140905 23:32:00.000', N'James', NULL, NULL)
END









