CREATE TABLE [Security].[Users] (
    [ID]                          UNIQUEIDENTIFIER CONSTRAINT [DF_Users_ID] DEFAULT (newsequentialid()) NOT NULL,
    [UserName]                    NVARCHAR (50)    NOT NULL,
    [Email]                       NVARCHAR (256)   NOT NULL,
    [Password]                    NVARCHAR (128)   NOT NULL,
    [PasswordSalt]                NVARCHAR (128)   NOT NULL,
    [PasswordVersion]             SMALLINT         NOT NULL,
    [IsLocked]                    BIT              CONSTRAINT [DF_Security_IsLocked] DEFAULT ((0)) NOT NULL,
    [IsEnabled]                   BIT              CONSTRAINT [DF_Security_IsEnabled] DEFAULT ((0)) NOT NULL,
    [ReenableToken]               UNIQUEIDENTIFIER NULL,
    [ResetPasswordToken]          UNIQUEIDENTIFIER NULL,
    [ResetPasswordTokenCreatedOn] DATETIME         NULL,
    [LastLoginDate]               DATETIME         NULL,
    [LastLoginToken]              UNIQUEIDENTIFIER NULL,
    [LastPasswordChangeDate]      DATETIME         NOT NULL,
    [LastLockoutDate]             DATETIME         NULL,
    [FailedPasswordAttemptCount]  SMALLINT         CONSTRAINT [DF_Security_FailedPasswordAttemptCount] DEFAULT ((0)) NOT NULL,
    [Notes]                       NVARCHAR (MAX)   NULL,
    [GroupAssociation]            BIGINT           CONSTRAINT [DF_Users_GroupAssociation] DEFAULT ((1)) NOT NULL,
    [CreatedOn]                   DATETIME         NOT NULL,
    [CreatedBy]                   NVARCHAR (50)    NOT NULL,
    [ModifiedOn]                  DATETIME         NULL,
    [ModifiedBy]                  NVARCHAR (50)    NULL,
    [ts]                          ROWVERSION       NOT NULL,
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UC_UsersEmail] UNIQUE NONCLUSTERED ([Email] ASC),
    CONSTRAINT [UC_UsersUserName] UNIQUE NONCLUSTERED ([UserName] ASC)
);

